create table
  public.users (
    id bigint generated by default as identity,
    "Fname" text null,
    "Lname" text null,
    "Email" text not null,
    "Password" text null,
    "Phone" text null,
    "Gender" character varying null,
    "Address" text null,
    "Age" date null,
    role text null,
    constraint users_pkey primary key (id, "Email"),
    constraint users_Email_key unique ("Email")
  ) tablespace pg_default;

  create table
  public.applicants (
    "Fname" text null,
    "Lname" text null,
    "Email" text not null,
    "Phone" integer null,
    "Gender" character varying null,
    "Address" text null,
    "Age" date null,
    constraint applicants_Email_key unique ("Email")
  ) tablespace pg_default;

  create table
  public."CAds" (
    "Company_Name" character varying not null,
    "Image" character varying not null,
    "CompanyAds" character varying null,
    constraint CAds_pkey primary key ("Company_Name")
  ) tablespace pg_default;

  create table
  public."CarPackages" (
    id bigint generated by default as identity,
    price character varying not null,
    type character varying null,
    "Personal Accident" character varying null,
    "COinsurance" character varying null,
    "AgencyCOinsurance" character varying null,
    "Roadside Assistance" character varying null,
    "Civil Liability" character varying null,
    "Police Report" character varying null,
    "Dfixing" character varying null,
    providerid bigint null,
    constraint CarPackages_pkey primary key (id),
    constraint CarPackages_providerid_fkey foreign key (providerid) references "Providers" (id)
  ) tablespace pg_default;

  create table
  public."Providers" (
    id bigint generated by default as identity,
    name character varying not null,
    image character varying null,
    constraint Providers_pkey primary key (id)
  ) tablespace pg_default;